---
branches:
    only:
        - master
language: python

python:
    - "3.7"

install:
    - pip install pytest
    - pip install pytest-mock
    - pip install pytest-cov
    - pip install pytest-flake8
    - pip install codecov
    - pip install -e .

script:
    - pytest --flake8 --cov

after_success:
    - codecov
