name: Coverage
on: [push, pull_request]
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: wntrblm/nox@2022.11.21
      with:
        python-versions: "3.7, 3.8, 3.9"
    - run: pip install poetry==1.3.1
    - run: nox --sessions tests-3.8 coverage
