name: Release
on:
  release:
    types: [published]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: wntrblm/nox@2022.11.21
      with:
        python-versions: "3.7, 3.8, 3.9"
    - run: pip install poetry==1.3.1
    - run: nox
    - run: poetry build
    - run: poetry publish --username=__token__ --password=${{ secrets.PYPI_TOKEN }}
